# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: gitversion/setup@0
  displayName: Install GitVersion
  inputs:
    versionSpec: '5.x'

- task: gitversion/execute@0
  displayName: Use GitVersion
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/src/'

- script: |
    echo FullSemVer: $(fullSemVer)
    echo ##vso[build.updatebuildnumber]$(fullSemVer)
  displayName: Export GitVersion results to variables

- task: DotNetCoreCLI@2
  displayName: 'restore'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
    verbosityRestore: 'Normal'

- task: DotNetCoreCLI@2
  displayName: 'build'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--no-restore -c Release'

- task: DotNetCoreCLI@2
  displayName: 'test'
  inputs:
    command: 'test'
    projects: '**/*Tests.csproj'
    arguments: '--no-build'

#- task: DotNetCoreCLI@2
#  displayName: 'publish'
#  inputs:
#    command: 'publish'
#    projects: '**/*.csproj'
#    arguments: '--no-build'

- task: DotNetCoreCLI@2
  displayName: 'pack'
  inputs:
    command: 'pack'
    projects: '**/MyLib.csproj'
    arguments: '--no-build'
